### ISSUE TITLE
Algoritmo não está retornado a qtde mínima de discos

### ISSUE THREAD

**Issue by dvriesman** [marcfreir/softplan-backend#1]
Enter the file sizes: 
90 50 30 30 10 50 8 85 5 95
Enter the tape/disk size: 
100
====
17 disks

Deveria ser: 5 discos né.
95 + 5 = 1 disco
85 + 8 = 2 discos
50 + 50 = 3 discos
90 + 10 = 4 discos
30 + 30 = 5 discos

**Comment by marcfreir** [comment]
A questão ficou um pouco confusa para mim.

Já que "É proibido colocar mais de 2 arquivos no mesmo disco." - conforme as instruções, para atender a Entrada com o Disco de Tamanho = 100 e os Arquivos: 20, 30, 50, 10, 15", a Saída deveria ser 3 discos e não 2, ou algum dos arquivos ficaria de fora.

Ex.: 20 e 30 é guardado em 1 disco; 50 e 10 em outro disco; e por ultimo o 15 em outro disco.

No caso do exemplo citado (array[] = {90, 50, 30, 30, 10, 50, 8, 85, 5, 95}) contém 10 elementos, ou seja, é par. No caso do exemplo dado na questão (array[] = {20, 30, 50, 10, 15}) contém 5 elementos, ou seja, é impar.

Meu entendimento foi baseado no exemplo dado na questão, por isso que causou uma certa confusão.

De qualquer forma, obrigado pelo feedback!

**Comment by marcfreir** [comment]
O algorítmo foi refeito para atender o teste de exemplo citado acima (valores: 90 50 30 30 10 50 8 85 5 95) e em conformidade ao teste de exemplo descrito na atividade.

O resultado obtido com os valores: 90, 50, 30, 30, 10, 50, 8, 85, 5, 95, foi "5 disks" e os valores da atividade (20, 30, 50, 10, 15) foi "2 disks".

**Refiz o código para poder fechar a issue (code review).**

Mais uma vez, obrigado!
